### PR TITLE
update imagestreams to registry.redhat.io

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@nicolaferraro @jamesnetherton  these changes are needed to switch to the new redhat registry.   I've made the PR against the branch that openshift/library is pulling from (GA), but you'll need to ensure these changes get into any upstream dev branches as well.

**Comment by jamesnetherton** [comment]
@bparees thanks. Is this safe to merge now? Is registry.redhat.io up and running?

Will registry.access.redhat.com continue to work?

Sorry for the dumb questions but just want to have some background on this change.

**Comment by bparees** [comment]
@jamesnetherton it's up if you use your RHN creds to auth.  There will be a service account token management feature coming "very soon".  So it's generally safe to merge, if someone is using these files directly they will have to setup their registry credentials though.

and yes the old registry will continue to work for now, but not indefinitely.

**Comment by aileenc** [comment]
Will this change have an impact on Fuse customers in that they now need to provide credentials?

**Comment by jamesnetherton** [comment]
See also: https://issues.jboss.org/browse/ENTESB-9319.

**Comment by bparees** [comment]
> Will this change have an impact on Fuse customers in that they now need to provide credentials?

I don't know enough about your customer/usage scenario to really answer that.

But eventually every redhat product should be pulling images from the new registry, which will require credentials.  When doing so on openshift, those credentials may be populated for you (depending how your imagestreams are defined, whether they reside in the openshift namespace, etc).

**Comment by bparees** [comment]
@jamesnetherton how can we move this forward?

**Comment by jamesnetherton** [comment]
I added this to the Fuse 7.2 branch in https://github.com/jboss-fuse/application-templates/commit/a3548ee41403c0ca32e396c28b2d0bb71eb886de.

It'll get merged onto the GA branch once 7.2 is released.

**Pull request closed without merging**
